/**
 * GrantOps seed data — the initial Funding Command Center contents.
 *
 * Everything here is a *starting* dataset the module boots with: the eight
 * entity profiles, the current (July 2026) + strategic 2026 funding
 * opportunities, a small document vault, and the ALLIE prompt library. It is
 * intentionally conservative — eligibility that isn't confirmed is left as
 * "verify", never assumed "yes" (business rule: preserve verify flags).
 *
 * The store (store.ts) clones this on first use; mutations never touch these
 * literals. When GrantOps moves onto Postgres later, this same shape becomes
 * the seed-on-first-use payload.
 */

import {
  computeFinalPriority,
  type EntityProfile,
  type FundingOpportunity,
  type GrantDocument,
} from "./types";

// A fixed "now" for seed timestamps so the module is deterministic without
// Date.now() at import time. Real records stamp their own times via the store.
const T0 = "2026-07-19T00:00:00.000Z";

// ─── Opportunity builder ─────────────────────────────────────────────────────
// Fills in the long list of TriState eligibility flags with a safe default of
// "verify" (never silently "yes"), so a seed entry only has to name what it
// actually knows. Also derives finalPriorityScore from the component scores.

type OppSeed = Omit<
  FundingOpportunity,
  | "id" | "finalPriorityScore" | "createdAt" | "updatedAt"
  | "blackMaleFounderEligible" | "blackOwnedEligible" | "minorityOwnedEligible"
  | "georgiaEligible" | "atlantaEligible" | "forProfitEligible" | "nonprofitRequired"
  | "womanOwnedRequired" | "veteranStatusRequired" | "physicalStorefrontRequired"
  | "revenueHistoryRequired" | "matchRequired" | "samGovRequired" | "mbeCertificationRequired"
> &
  Partial<Pick<
    FundingOpportunity,
    | "blackMaleFounderEligible" | "blackOwnedEligible" | "minorityOwnedEligible"
    | "georgiaEligible" | "atlantaEligible" | "forProfitEligible" | "nonprofitRequired"
    | "womanOwnedRequired" | "veteranStatusRequired" | "physicalStorefrontRequired"
    | "revenueHistoryRequired" | "matchRequired" | "samGovRequired" | "mbeCertificationRequired"
  >>;

function opp(id: string, s: OppSeed): FundingOpportunity {
  const flags = {
    blackMaleFounderEligible: s.blackMaleFounderEligible ?? "verify",
    blackOwnedEligible: s.blackOwnedEligible ?? "verify",
    minorityOwnedEligible: s.minorityOwnedEligible ?? "verify",
    georgiaEligible: s.georgiaEligible ?? "verify",
    atlantaEligible: s.atlantaEligible ?? "verify",
    forProfitEligible: s.forProfitEligible ?? "verify",
    nonprofitRequired: s.nonprofitRequired ?? "no",
    womanOwnedRequired: s.womanOwnedRequired ?? "no",
    veteranStatusRequired: s.veteranStatusRequired ?? "no",
    physicalStorefrontRequired: s.physicalStorefrontRequired ?? "no",
    revenueHistoryRequired: s.revenueHistoryRequired ?? "verify",
    matchRequired: s.matchRequired ?? "no",
    samGovRequired: s.samGovRequired ?? "no",
    mbeCertificationRequired: s.mbeCertificationRequired ?? "no",
  };
  const scored = {
    strategicFitScore: s.strategicFitScore,
    urgencyScore: s.urgencyScore,
    fundingValueScore: s.fundingValueScore,
    probabilityScore: s.probabilityScore,
    complexityDrag: s.complexityDrag,
  };
  return {
    ...s,
    ...flags,
    id,
    finalPriorityScore: computeFinalPriority(scored),
    createdAt: T0,
    updatedAt: T0,
  };
}

// ─── Entity profiles ─────────────────────────────────────────────────────────

const ent = (
  id: string,
  p: Omit<EntityProfile, "id" | "createdAt" | "updatedAt">,
): EntityProfile => ({ ...p, id, createdAt: T0, updatedAt: T0 });

export const SEED_ENTITIES: EntityProfile[] = [
  ent("ent-amg", {
    entityCode: "AMG",
    entityName: "Apex Meridian Group",
    entityType: "holding_company",
    legalName: "Apex Meridian Group LLC",
    shortName: "AMG",
    description:
      "The holding company / coordination layer. AMG researches, scores, and coordinates funding but is generally NOT the direct applicant — an operating entity applies. Preserve this: AMG coordinates, operating entities apply.",
    fundingRole: "coordinator",
    bestFundingLanes: ["founder_capacity", "certification_contracting"],
    einStatus: "ready",
    stateRegistrationStatus: "ready",
    operatingAgreementStatus: "in_progress",
    bankAccountStatus: "ready",
    naicsCodes: [],
    samGovStatus: "not_started",
    ueiStatus: "not_started",
    grantsGovStatus: "not_started",
    mbeCertificationStatus: "not_started",
    gmsdcStatus: "not_started",
    doasStatus: "not_started",
    sba8aStatus: "not_started",
    hubzoneStatus: "n_a",
    defaultFounder: "Both",
    notes: "Coordinator only. Route applications to the operating entity that best fits the program.",
  }),
  ent("ent-hvn", {
    entityCode: "HVN",
    entityName: "HVN Havenry",
    entityType: "operating_company",
    legalName: "HVN Havenry LLC",
    shortName: "HVN",
    description:
      "Retail / e-commerce home-atmosphere brand (candles, incense, home goods). Strongest fit for small-business, retail, and digital-readiness grants.",
    fundingRole: "applicant",
    bestFundingLanes: ["retail_ecommerce", "local_atlanta", "creative_media"],
    einStatus: "ready",
    stateRegistrationStatus: "ready",
    operatingAgreementStatus: "in_progress",
    bankAccountStatus: "ready",
    website: "https://hvnhavenry.com",
    naicsCodes: ["453998", "454110"],
    samGovStatus: "not_started",
    ueiStatus: "not_started",
    grantsGovStatus: "not_started",
    mbeCertificationStatus: "not_started",
    gmsdcStatus: "not_started",
    doasStatus: "not_started",
    sba8aStatus: "not_started",
    hubzoneStatus: "n_a",
    defaultFounder: "Rahmel",
    notes: "Primary applicant for retail / small-business / e-commerce programs.",
  }),
  ent("ent-3e", {
    entityCode: "3E",
    entityName: "3E Dynamics",
    entityType: "operating_company",
    legalName: "3E Dynamics LLC",
    shortName: "3E",
    description:
      "Technology / engineering venture — the strongest candidate for R&D and deep-tech non-dilutive funding (SBIR/STTR, NSF, DOE, NVIDIA Inception).",
    fundingRole: "applicant",
    bestFundingLanes: ["technology", "manufacturing"],
    einStatus: "in_progress",
    stateRegistrationStatus: "in_progress",
    operatingAgreementStatus: "not_started",
    bankAccountStatus: "not_started",
    naicsCodes: ["541715"],
    samGovStatus: "not_started",
    ueiStatus: "not_started",
    grantsGovStatus: "not_started",
    mbeCertificationStatus: "not_started",
    gmsdcStatus: "not_started",
    doasStatus: "not_started",
    sba8aStatus: "not_started",
    hubzoneStatus: "n_a",
    defaultFounder: "Haneef",
    notes: "SBIR/STTR path requires SAM.gov + UEI + Grants.gov registration well ahead of deadlines — verify and start early.",
  }),
  ent("ent-giq", {
    entityCode: "GovernanceIQ",
    entityName: "GovernanceIQ",
    entityType: "operating_company",
    legalName: "GovernanceIQ LLC",
    shortName: "GovernanceIQ",
    description:
      "Governance / compliance software concept. Fits SaaS, civic-tech, and SBIR software topics once incorporated and product-defined.",
    fundingRole: "applicant",
    bestFundingLanes: ["technology", "certification_contracting"],
    einStatus: "not_started",
    stateRegistrationStatus: "not_started",
    operatingAgreementStatus: "not_started",
    bankAccountStatus: "not_started",
    naicsCodes: ["541511"],
    samGovStatus: "not_started",
    ueiStatus: "not_started",
    grantsGovStatus: "not_started",
    mbeCertificationStatus: "not_started",
    gmsdcStatus: "not_started",
    doasStatus: "not_started",
    sba8aStatus: "not_started",
    hubzoneStatus: "n_a",
    defaultFounder: "Haneef",
    notes: "Early-stage concept — verify incorporation status before naming it as an applicant.",
  }),
  ent("ent-rmi", {
    entityCode: "RMI",
    entityName: "RMoor Industries",
    entityType: "operating_company",
    legalName: "RMoor Industries Ltd. Co.",
    shortName: "RMI",
    description:
      "Parent industrial/creative operating company. Home for manufacturing, creative-media, and content-production funding lanes.",
    fundingRole: "applicant",
    bestFundingLanes: ["manufacturing", "creative_media"],
    einStatus: "ready",
    stateRegistrationStatus: "ready",
    operatingAgreementStatus: "ready",
    bankAccountStatus: "ready",
    naicsCodes: ["512110", "339999"],
    samGovStatus: "not_started",
    ueiStatus: "not_started",
    grantsGovStatus: "not_started",
    mbeCertificationStatus: "not_started",
    gmsdcStatus: "not_started",
    doasStatus: "not_started",
    sba8aStatus: "not_started",
    hubzoneStatus: "n_a",
    defaultFounder: "Rahmel",
  }),
  ent("ent-rmg", {
    entityCode: "RMG",
    entityName: "RMG (Creator OS)",
    entityType: "operating_company",
    legalName: "RMG",
    shortName: "RMG",
    description:
      "Creator-economy / media-production line. Best fit for creative, documentary, and content-focused funding (e.g. Southern Documentary Fund).",
    fundingRole: "applicant",
    bestFundingLanes: ["creative_media", "technology"],
    einStatus: "in_progress",
    stateRegistrationStatus: "in_progress",
    operatingAgreementStatus: "not_started",
    bankAccountStatus: "in_progress",
    naicsCodes: ["512110"],
    samGovStatus: "not_started",
    ueiStatus: "not_started",
    grantsGovStatus: "not_started",
    mbeCertificationStatus: "not_started",
    gmsdcStatus: "not_started",
    doasStatus: "not_started",
    sba8aStatus: "not_started",
    hubzoneStatus: "n_a",
    defaultFounder: "Rahmel",
  }),
  ent("ent-rahmel", {
    entityCode: "Rahmel",
    entityName: "Rahmel Moore",
    entityType: "founder",
    legalName: "Rahmel Moore",
    shortName: "Rahmel",
    description:
      "Founder. Eligible in his own name for founder-capacity, fellowship, and individual creator grants where the applicant is a person, not an entity.",
    fundingRole: "founder_applicant",
    bestFundingLanes: ["founder_capacity", "creative_media"],
    einStatus: "n_a",
    stateRegistrationStatus: "n_a",
    operatingAgreementStatus: "n_a",
    bankAccountStatus: "ready",
    naicsCodes: [],
    samGovStatus: "n_a",
    ueiStatus: "n_a",
    grantsGovStatus: "n_a",
    mbeCertificationStatus: "not_started",
    gmsdcStatus: "not_started",
    doasStatus: "not_started",
    sba8aStatus: "not_started",
    hubzoneStatus: "n_a",
    defaultFounder: "Rahmel",
  }),
  ent("ent-haneef", {
    entityCode: "Haneef",
    entityName: "Haneef Elisha",
    entityType: "founder",
    legalName: "Haneef Elisha",
    shortName: "Haneef",
    description:
      "Founder. Eligible in his own name for founder-capacity, fellowship, and individual creator/technical grants where the applicant is a person.",
    fundingRole: "founder_applicant",
    bestFundingLanes: ["founder_capacity", "technology"],
    einStatus: "n_a",
    stateRegistrationStatus: "n_a",
    operatingAgreementStatus: "n_a",
    bankAccountStatus: "ready",
    naicsCodes: [],
    samGovStatus: "n_a",
    ueiStatus: "n_a",
    grantsGovStatus: "n_a",
    mbeCertificationStatus: "not_started",
    gmsdcStatus: "not_started",
    doasStatus: "not_started",
    sba8aStatus: "not_started",
    hubzoneStatus: "n_a",
    defaultFounder: "Haneef",
  }),
];

// ─── Opportunities ───────────────────────────────────────────────────────────
// Current urgent (July 2026) + strategic 2026. Scores are ALLIE's first-pass
// estimates; CAPPO adjusts on review. Eligibility left "verify" unless known.

export const SEED_OPPORTUNITIES: FundingOpportunity[] = [
  opp("opp-big-skip", {
    opportunityName: "The Big Skip — Summer Grant",
    fundingOrganization: "Skip (formerly Hello Alice partner)",
    programType: "grant",
    status: "apply_now",
    deadline: "2026-07-31",
    fundingAmount: 10000,
    awardType: "cash",
    bestApplicantEntity: "HVN",
    secondaryApplicantEntity: "RMI",
    strategicLane: "retail_ecommerce",
    forProfitEligible: "yes",
    blackMaleFounderEligible: "yes",
    revenueHistoryRequired: "verify",
    requiredDocuments: ["business_summary", "founder_bio", "use_of_funds"],
    applicationUrl: "https://helloskip.com",
    sourceReliability: "aggregator",
    complexity: "low",
    strategicFitScore: 9,
    urgencyScore: 10,
    fundingValueScore: 6,
    probabilityScore: 6,
    complexityDrag: 2,
    recommendation: "apply_now",
    cappoDecision: "pending",
    humanOwner: "Rahmel",
    outcome: "pending",
    allieNotes: "Fast, low-lift $10K for HVN. Confirm exact eligibility window + whether an active Skip membership is required before submitting.",
  }),
  opp("opp-galaxy", {
    opportunityName: "Galaxy Grants",
    fundingOrganization: "Galaxy (creative small-business fund)",
    programType: "grant",
    status: "apply_now",
    deadline: "2026-07-31",
    fundingAmount: 4250,
    awardType: "cash",
    bestApplicantEntity: "HVN",
    strategicLane: "creative_media",
    forProfitEligible: "yes",
    requiredDocuments: ["business_summary", "founder_bio", "product_photos"],
    sourceReliability: "aggregator",
    complexity: "low",
    strategicFitScore: 7,
    urgencyScore: 9,
    fundingValueScore: 4,
    probabilityScore: 5,
    complexityDrag: 2,
    recommendation: "apply_now",
    cappoDecision: "pending",
    humanOwner: "Rahmel",
    outcome: "pending",
    allieNotes: "Creative-leaning micro-grant; HVN's brand story is a strength here.",
  }),
  opp("opp-verizon", {
    opportunityName: "Verizon Small Business Digital Ready — $10K Grant",
    fundingOrganization: "Verizon / LISC",
    programType: "grant",
    status: "verify_first",
    deadline: "2026-07-31",
    fundingAmount: 10000,
    awardType: "cash",
    bestApplicantEntity: "HVN",
    strategicLane: "retail_ecommerce",
    forProfitEligible: "yes",
    revenueHistoryRequired: "verify",
    requiredDocuments: ["business_summary", "founder_bio", "use_of_funds"],
    applicationUrl: "https://www.verizon.com/business/small-business-essentials/digital-ready/",
    sourceReliability: "official",
    complexity: "medium",
    strategicFitScore: 8,
    urgencyScore: 9,
    fundingValueScore: 6,
    probabilityScore: 5,
    complexityDrag: 4,
    recommendation: "verify_first",
    cappoDecision: "pending",
    humanOwner: "Rahmel",
    outcome: "pending",
    allieNotes: "Requires completing a set number of Digital Ready courses to be eligible — verify that prerequisite and the current grant cycle before committing effort.",
  }),
  opp("opp-skip-instant", {
    opportunityName: "Skip Instant Grants",
    fundingOrganization: "Skip",
    programType: "grant",
    status: "verify_first",
    deadline: null,
    rollingDeadline: true,
    fundingAmount: 1000,
    awardType: "cash",
    bestApplicantEntity: "HVN",
    strategicLane: "retail_ecommerce",
    forProfitEligible: "yes",
    requiredDocuments: ["business_summary", "founder_bio"],
    applicationUrl: "https://helloskip.com",
    sourceReliability: "aggregator",
    complexity: "low",
    strategicFitScore: 5,
    urgencyScore: 4,
    fundingValueScore: 2,
    probabilityScore: 5,
    complexityDrag: 1,
    recommendation: "verify_first",
    cappoDecision: "pending",
    humanOwner: "Rahmel",
    outcome: "pending",
    allieNotes: "Small rolling micro-grants, often tied to a paid Skip membership — verify whether the membership cost is worth it vs. the award.",
  }),
  opp("opp-nvidia", {
    opportunityName: "NVIDIA Inception",
    fundingOrganization: "NVIDIA",
    programType: "in_kind_credit",
    status: "verify_first",
    deadline: null,
    rollingDeadline: true,
    fundingAmount: null,
    awardType: "in_kind",
    bestApplicantEntity: "3E",
    secondaryApplicantEntity: "GovernanceIQ",
    strategicLane: "technology",
    forProfitEligible: "yes",
    requiredDocuments: ["business_summary", "pitch_deck"],
    applicationUrl: "https://www.nvidia.com/en-us/startups/",
    sourceReliability: "official",
    complexity: "low",
    strategicFitScore: 7,
    urgencyScore: 3,
    fundingValueScore: 5,
    probabilityScore: 7,
    complexityDrag: 2,
    recommendation: "verify_first",
    cappoDecision: "pending",
    humanOwner: "Haneef",
    outcome: "pending",
    allieNotes: "Zero-equity accelerator/credits program (GPU credits, technical resources). Confirm 3E is incorporated enough to enroll; not cash.",
  }),
  opp("opp-aws-activate", {
    opportunityName: "AWS Activate",
    fundingOrganization: "Amazon Web Services",
    programType: "in_kind_credit",
    status: "verify_first",
    deadline: null,
    rollingDeadline: true,
    fundingAmount: null,
    awardType: "credit",
    bestApplicantEntity: "3E",
    secondaryApplicantEntity: "RMG",
    strategicLane: "technology",
    forProfitEligible: "yes",
    requiredDocuments: ["business_summary"],
    applicationUrl: "https://aws.amazon.com/activate/",
    sourceReliability: "official",
    complexity: "low",
    strategicFitScore: 6,
    urgencyScore: 3,
    fundingValueScore: 5,
    probabilityScore: 7,
    complexityDrag: 2,
    recommendation: "verify_first",
    cappoDecision: "pending",
    humanOwner: "Haneef",
    outcome: "pending",
    allieNotes: "Cloud credits (in-kind, not cash). Often needs an accelerator/VC affiliation for the larger tiers — verify which tier is reachable.",
  }),
  opp("opp-startup-runway", {
    opportunityName: "Startup Runway",
    fundingOrganization: "Startup Runway Foundation",
    programType: "pitch_competition",
    status: "verify_first",
    deadline: null,
    rollingDeadline: true,
    fundingAmount: 10000,
    awardType: "cash",
    bestApplicantEntity: "3E",
    secondaryApplicantEntity: "HVN",
    strategicLane: "local_atlanta",
    forProfitEligible: "yes",
    georgiaEligible: "yes",
    atlantaEligible: "yes",
    blackOwnedEligible: "yes",
    requiredDocuments: ["pitch_deck", "business_summary", "founder_bio"],
    applicationUrl: "https://www.startuprunway.org",
    sourceReliability: "official",
    complexity: "medium",
    strategicFitScore: 8,
    urgencyScore: 4,
    fundingValueScore: 6,
    probabilityScore: 6,
    complexityDrag: 3,
    recommendation: "verify_first",
    cappoDecision: "pending",
    humanOwner: "Haneef",
    outcome: "pending",
    allieNotes: "Atlanta-based, focused on underrepresented founders — strong strategic fit. Confirm current application window (cohort-based).",
  }),
  opp("opp-atdc", {
    opportunityName: "ATDC Accelerate",
    fundingOrganization: "Advanced Technology Development Center (Georgia Tech)",
    programType: "accelerator",
    status: "verify_first",
    deadline: null,
    rollingDeadline: true,
    fundingAmount: null,
    awardType: "in_kind",
    bestApplicantEntity: "3E",
    secondaryApplicantEntity: "GovernanceIQ",
    strategicLane: "technology",
    forProfitEligible: "yes",
    georgiaEligible: "yes",
    requiredDocuments: ["business_summary", "pitch_deck"],
    applicationUrl: "https://atdc.org",
    sourceReliability: "official",
    complexity: "medium",
    strategicFitScore: 7,
    urgencyScore: 3,
    fundingValueScore: 4,
    probabilityScore: 6,
    complexityDrag: 3,
    recommendation: "verify_first",
    cappoDecision: "pending",
    humanOwner: "Haneef",
    outcome: "pending",
    allieNotes: "Georgia Tech accelerator — verify whether the relevant program is zero-equity (most ATDC programs are non-dilutive, but confirm the specific track).",
  }),

  // ── Strategic 2026 ────────────────────────────────────────────────────────
  opp("opp-nsf-sbir", {
    opportunityName: "NSF SBIR/STTR Phase I",
    fundingOrganization: "National Science Foundation",
    programType: "grant",
    status: "verify_first",
    deadline: "2026-11-04",
    fundingAmount: 305000,
    awardType: "cash",
    bestApplicantEntity: "3E",
    secondaryApplicantEntity: "GovernanceIQ",
    strategicLane: "technology",
    forProfitEligible: "yes",
    samGovRequired: "yes",
    matchRequired: "no",
    revenueHistoryRequired: "no",
    requiredDocuments: ["pitch_deck", "business_summary", "project_plan", "budget", "founder_bio", "capability_statement"],
    applicationUrl: "https://seedfund.nsf.gov",
    sourceReliability: "official",
    complexity: "high",
    strategicFitScore: 9,
    urgencyScore: 6,
    fundingValueScore: 10,
    probabilityScore: 4,
    complexityDrag: 8,
    recommendation: "verify_first",
    cappoDecision: "pending",
    humanOwner: "Haneef",
    outcome: "pending",
    allieNotes: "Flagship non-dilutive R&D grant (~$305K, no equity). Requires a Project Pitch accepted BEFORE the full proposal, plus SAM.gov/UEI/Grants.gov registration (weeks of lead time). Start registrations now for 3E.",
  }),
  opp("opp-doe-sbir", {
    opportunityName: "DOE SBIR/STTR",
    fundingOrganization: "U.S. Department of Energy",
    programType: "grant",
    status: "watchlist",
    deadline: null,
    rollingDeadline: false,
    fundingAmount: 200000,
    awardType: "cash",
    bestApplicantEntity: "3E",
    strategicLane: "technology",
    forProfitEligible: "yes",
    samGovRequired: "yes",
    requiredDocuments: ["pitch_deck", "business_summary", "project_plan", "budget"],
    applicationUrl: "https://science.osti.gov/sbir",
    sourceReliability: "official",
    complexity: "high",
    strategicFitScore: 7,
    urgencyScore: 3,
    fundingValueScore: 9,
    probabilityScore: 4,
    complexityDrag: 8,
    recommendation: "watchlist",
    cappoDecision: "pending",
    humanOwner: "Haneef",
    outcome: "pending",
    allieNotes: "Topic-driven; only pursue if a released DOE topic matches 3E's technology. Watch for the annual Phase I release schedule.",
  }),
  opp("opp-invest-atlanta", {
    opportunityName: "Invest Atlanta — Small Business Improvement Grant (SBIG)",
    fundingOrganization: "Invest Atlanta",
    programType: "grant",
    status: "verify_first",
    deadline: null,
    rollingDeadline: true,
    fundingAmount: 40000,
    awardType: "reimbursement",
    bestApplicantEntity: "HVN",
    strategicLane: "local_atlanta",
    forProfitEligible: "yes",
    georgiaEligible: "yes",
    atlantaEligible: "verify",
    physicalStorefrontRequired: "verify",
    matchRequired: "yes",
    requiredDocuments: ["business_summary", "budget", "use_of_funds"],
    applicationUrl: "https://www.investatlanta.com",
    sourceReliability: "official",
    complexity: "high",
    strategicFitScore: 6,
    urgencyScore: 3,
    fundingValueScore: 8,
    probabilityScore: 3,
    complexityDrag: 7,
    recommendation: "verify_first",
    cappoDecision: "pending",
    humanOwner: "Rahmel",
    outcome: "pending",
    allieNotes: "Reimbursement-based and usually tied to a physical location inside a specific Atlanta improvement district + a match. Verify HVN's address eligibility before pursuing.",
  }),
  opp("opp-worldcup-popup", {
    opportunityName: "Atlanta World Cup Pop-Up Fund",
    fundingOrganization: "Atlanta host-committee / local partners",
    programType: "grant",
    status: "watchlist",
    deadline: null,
    rollingDeadline: false,
    fundingAmount: 15000,
    awardType: "cash",
    bestApplicantEntity: "HVN",
    strategicLane: "local_atlanta",
    forProfitEligible: "yes",
    georgiaEligible: "yes",
    atlantaEligible: "verify",
    requiredDocuments: ["business_summary", "product_photos"],
    sourceReliability: "needs_confirmation",
    complexity: "medium",
    strategicFitScore: 6,
    urgencyScore: 4,
    fundingValueScore: 6,
    probabilityScore: 4,
    complexityDrag: 3,
    recommendation: "watchlist",
    cappoDecision: "pending",
    humanOwner: "Rahmel",
    outcome: "pending",
    allieNotes: "Tied to 2026 World Cup activations in Atlanta. Source needs confirmation — verify the fund actually exists and its terms before investing effort.",
  }),
  opp("opp-southern-doc", {
    opportunityName: "Southern Documentary Fund",
    fundingOrganization: "Southern Documentary Fund",
    programType: "grant",
    status: "watchlist",
    deadline: null,
    rollingDeadline: false,
    fundingAmount: 20000,
    awardType: "cash",
    bestApplicantEntity: "RMG",
    secondaryApplicantEntity: "Rahmel",
    strategicLane: "creative_media",
    forProfitEligible: "verify",
    nonprofitRequired: "verify",
    requiredDocuments: ["project_plan", "budget", "founder_bio"],
    applicationUrl: "https://www.southerndocfund.org",
    sourceReliability: "official",
    complexity: "medium",
    strategicFitScore: 5,
    urgencyScore: 3,
    fundingValueScore: 6,
    probabilityScore: 4,
    complexityDrag: 4,
    recommendation: "watchlist",
    cappoDecision: "pending",
    humanOwner: "Rahmel",
    outcome: "pending",
    allieNotes: "Often requires fiscal sponsorship for for-profit applicants — verify whether a fiscal-sponsor path is needed and worth it for an RMG documentary project.",
  }),
];

// ─── Document vault (starter) ────────────────────────────────────────────────

const doc = (
  id: string,
  d: Omit<GrantDocument, "id" | "createdAt" | "updatedAt">,
): GrantDocument => ({ ...d, id, createdAt: T0, updatedAt: T0 });

export const SEED_DOCUMENTS: GrantDocument[] = [
  doc("doc-hvn-summary", {
    documentName: "HVN Havenry — Business Summary",
    documentType: "business_summary",
    relatedEntity: "HVN",
    status: "draft",
    refreshFrequency: "quarterly",
    notes: "Reusable 1-page overview for retail/small-business grants.",
  }),
  doc("doc-rahmel-bio", {
    documentName: "Rahmel Moore — Founder Bio",
    documentType: "founder_bio",
    relatedEntity: "Rahmel",
    status: "draft",
    refreshFrequency: "as needed",
  }),
  doc("doc-haneef-bio", {
    documentName: "Haneef Elisha — Founder Bio",
    documentType: "founder_bio",
    relatedEntity: "Haneef",
    status: "draft",
    refreshFrequency: "as needed",
  }),
  doc("doc-hvn-ein", {
    documentName: "HVN Havenry — EIN Letter",
    documentType: "ein_letter",
    relatedEntity: "HVN",
    status: "uploaded",
    refreshFrequency: "n/a",
  }),
  doc("doc-3e-capability", {
    documentName: "3E Dynamics — Capability Statement",
    documentType: "capability_statement",
    relatedEntity: "3E",
    status: "missing",
    refreshFrequency: "as needed",
    notes: "Needed for SBIR/STTR + contracting. Draft once 3E is incorporated.",
  }),
];

// ─── ALLIE prompt library ────────────────────────────────────────────────────

export interface AiPrompt {
  id: string;
  title: string;
  category: "research" | "eligibility" | "drafting" | "scoring" | "review";
  description: string;
  prompt: string;
}

export const SEED_PROMPTS: AiPrompt[] = [
  {
    id: "prompt-research-scan",
    title: "Weekly opportunity scan",
    category: "research",
    description: "ALLIE sweeps for new funding matches across AMG's operating entities.",
    prompt:
      "Act as ALLIE, AMG's Director of Operations for GrantOps. Find funding opportunities (grants, non-dilutive credits, pitch competitions) newly open or closing in the next 45 days that fit at least one of: HVN Havenry (retail/e-commerce home goods, Atlanta, Black-male-founder-led), 3E Dynamics (deep tech / R&D), or RMG (creator media). For each: name, funder, amount, award type (cash/credit/loan/equity), deadline, application URL, and the ONE best-fit entity. Flag anything that is women-only, nonprofit-only, a loan, or equity-taking. Do NOT assume eligibility — mark unknowns as 'verify'.",
  },
  {
    id: "prompt-eligibility-check",
    title: "Eligibility verification",
    category: "eligibility",
    description: "Confirm a specific program's real requirements before we invest effort.",
    prompt:
      "Act as ALLIE. For the funding program I name, verify from the OFFICIAL source: (1) entity-type eligibility (for-profit vs nonprofit), (2) any women-only / veteran-only / minority requirement, (3) geography (Georgia/Atlanta), (4) revenue or operating-history minimums, (5) match/cost-share, (6) required registrations (SAM.gov/UEI), (7) whether it is a grant, loan, tax credit, or equity deal. Cite the source URL for each. If a requirement can't be confirmed, mark it 'verify' — never assume 'yes'. End with a one-line recommendation: Apply Now / Verify First / Watchlist / Reject, and why.",
  },
  {
    id: "prompt-score",
    title: "Score an opportunity",
    category: "scoring",
    description: "Produce the five component scores that feed the priority formula.",
    prompt:
      "Act as ALLIE. Score this opportunity on the GrantOps 0–10 scale for each factor: Strategic Fit, Urgency (deadline proximity + entity readiness), Funding Value, Probability of Award, and Complexity Drag (how much work/registration it requires). Briefly justify each. The system computes Final Priority = Fit·0.30 + Urgency·0.25 + Value·0.20 + Probability·0.15 − ComplexityDrag·0.10.",
  },
  {
    id: "prompt-narrative",
    title: "Draft application narrative",
    category: "drafting",
    description: "First-pass narrative for founder review — never auto-submitted.",
    prompt:
      "Act as ALLIE. Draft a first-pass application narrative for the named opportunity and applicant entity. Use only facts I provide or that are in the entity profile — do not invent revenue, headcount, or metrics. Produce: (1) business summary, (2) use of funds, (3) impact statement. Mark any place that needs a real number with [VERIFY]. This is a DRAFT for founder review and human submission only — it will not be auto-submitted anywhere.",
  },
  {
    id: "prompt-cappo-review",
    title: "CAPPO governance review",
    category: "review",
    description: "Executive-Director decision framing for the review queue.",
    prompt:
      "Act as CAPPO, AMG's Executive Director. Given this scored opportunity and its risk flags, decide: Approve to Apply, Reject, Defer, or Need More Info — and name the single operating entity that should apply (never AMG directly). State the governance rationale in 2–3 sentences: strategic alignment, capital-type fit (cash vs credit vs dilutive), and readiness. If a human approval or a 'verify' flag is outstanding, require it before approving submission.",
  },
];
